/**
 * @file    Os.h
 * @brief   AUTOSAR CP R25-11 — Operating System
 * @details Implements AUTOSAR_CP_SWS_OS (R25-11)
 *          Functional Cluster: System Services
 *
 * AUTOSAR Document: AUTOSAR_CP_SWS_OS
 * Version        : R25-11
 */
#ifndef OS_H
#define OS_H

#include "Std_Types.h"

/* ================================================================
 * OS Type Definitions  [SWS_Os_00008]
 * ================================================================ */
typedef uint8   TaskType;
typedef uint8   TaskStateType;
typedef uint8   EventMaskType;
typedef uint8   ResourceType;
typedef uint8   ISRType;
typedef uint8   AppModeType;
typedef uint8   CounterType;
typedef uint32  TickType;
typedef uint8   AlarmType;
typedef uint8   ScheduleTableType;
typedef uint8   CoreIdType;
typedef uint8   ApplicationType;

typedef struct {
    TickType maxallowedvalue;
    TickType ticksperbase;
    TickType mincycle;
} AlarmBaseType;

typedef struct {
    TaskType  task;
    EventMaskType event;
} TaskRefType;

/* ================================================================
 * Task States
 * ================================================================ */
#define RUNNING    ((TaskStateType)0x00u)
#define WAITING    ((TaskStateType)0x01u)
#define READY      ((TaskStateType)0x02u)
#define SUSPENDED  ((TaskStateType)0x03u)

/* ================================================================
 * OS Status Codes  [SWS_Os_00090]
 * ================================================================ */
typedef uint8 StatusType;
#define E_OS_ACCESS     ((StatusType)0x01u)
#define E_OS_CALLEVEL   ((StatusType)0x02u)
#define E_OS_ID         ((StatusType)0x03u)
#define E_OS_LIMIT      ((StatusType)0x04u)
#define E_OS_NOFUNC     ((StatusType)0x05u)
#define E_OS_RESOURCE   ((StatusType)0x06u)
#define E_OS_STATE      ((StatusType)0x07u)
#define E_OS_VALUE      ((StatusType)0x08u)

/* ================================================================
 * Task IDs (project-specific, generated by configuration tool)
 * ================================================================ */
#define TASK_INIT       ((TaskType)0x00u)
#define TASK_10MS       ((TaskType)0x01u)
#define TASK_100MS      ((TaskType)0x02u)
#define TASK_BACKGROUND ((TaskType)0x03u)

/* ================================================================
 * API — OSEK/VDX + AUTOSAR extensions
 * ================================================================ */

/* --- Task Management --- */
StatusType ActivateTask(TaskType TaskID);
StatusType TerminateTask(void);
StatusType ChainTask(TaskType TaskID);
StatusType Schedule(void);
StatusType GetTaskID(TaskType* TaskID);
StatusType GetTaskState(TaskType TaskID, TaskStateType* State);

/* --- Event Mechanism --- */
StatusType SetEvent(TaskType TaskID, EventMaskType Mask);
StatusType ClearEvent(EventMaskType Mask);
StatusType GetEvent(TaskType TaskID, EventMaskType* Mask);
StatusType WaitEvent(EventMaskType Mask);

/* --- Resource Management --- */
StatusType GetResource(ResourceType ResID);
StatusType ReleaseResource(ResourceType ResID);

/* --- Alarms --- */
StatusType GetAlarmBase(AlarmType AlarmID, AlarmBaseType* Info);
StatusType GetAlarm(AlarmType AlarmID, TickType* Tick);
StatusType SetRelAlarm(AlarmType AlarmID, TickType increment, TickType cycle);
StatusType SetAbsAlarm(AlarmType AlarmID, TickType start, TickType cycle);
StatusType CancelAlarm(AlarmType AlarmID);

/* --- OS Control --- */
AppModeType GetActiveApplicationMode(void);
void StartOS(AppModeType Mode);
void ShutdownOS(StatusType Error);

/* --- Interrupt Control --- */
void DisableAllInterrupts(void);
void EnableAllInterrupts(void);
void SuspendAllInterrupts(void);
void ResumeAllInterrupts(void);
void SuspendOSInterrupts(void);
void ResumeOSInterrupts(void);

/* --- Timing Protection (AUTOSAR extension) --- */
void Os_Init(void);
CoreIdType GetCoreID(void);
uint32 Os_GetExecutionTime(void);

#endif /* OS_H */
