/**
 * @file    NvM.h
 * @brief   AUTOSAR CP R25-11 — NVRAM Manager
 * @details Implements AUTOSAR_CP_SWS_NVRAMManager (R25-11)
 *          Functional Cluster: Memory Services
 *
 * AUTOSAR Document: AUTOSAR_CP_SWS_NVRAMManager
 * Version        : R25-11
 */
#ifndef NVM_H
#define NVM_H

#include "Std_Types.h"

/* ================================================================
 * Type Definitions
 * ================================================================ */
typedef uint16 NvM_BlockIdType;        /**< Block identifier */

typedef enum {
    NVM_REQ_OK              = 0x00u,
    NVM_REQ_NOT_OK          = 0x01u,
    NVM_REQ_PENDING         = 0x02u,
    NVM_REQ_INTEGRITY_FAILED = 0x03u,
    NVM_REQ_BLOCK_SKIPPED   = 0x04u,
    NVM_REQ_NV_INVALIDATED  = 0x05u,
    NVM_REQ_CANCELED        = 0x06u,
    NVM_REQ_REDUNDANCY_FAILED = 0x07u,
    NVM_REQ_RESTORED_FROM_ROM = 0x08u
} NvM_RequestResultType;

/* Block IDs (project-specific, generated by tool) */
#define NVM_BLOCK_ID_CONFIG_DATA    ((NvM_BlockIdType)0x0002u)
#define NVM_BLOCK_ID_CALIB_DATA     ((NvM_BlockIdType)0x0003u)
#define NVM_BLOCK_ID_DTC_MIRROR     ((NvM_BlockIdType)0x0004u)
#define NVM_BLOCK_ID_ECU_COUNTER    ((NvM_BlockIdType)0x0005u)
#define NVM_BLOCK_ID_VEHICLE_DATA   ((NvM_BlockIdType)0x0006u)

/* ================================================================
 * API  [SWS_NvM_00012 .. SWS_NvM_00616]
 * ================================================================ */

/** Initialize NvM and restore all "init on first use" blocks [SWS_NvM_00447] */
void           NvM_Init(const void* ConfigPtr);

/** Read all blocks at startup [SWS_NvM_00460] */
void           NvM_ReadAll(void);

/** Write all modified blocks at shutdown [SWS_NvM_00461] */
void           NvM_WriteAll(void);

/** Cancel current operation [SWS_NvM_00462] */
void           NvM_CancelWriteAll(void);

/** Read single block to RAM [SWS_NvM_00012] */
Std_ReturnType NvM_ReadBlock(NvM_BlockIdType BlockId, void* NvM_DstPtr);

/** Write RAM to NV memory [SWS_NvM_00013] */
Std_ReturnType NvM_WriteBlock(NvM_BlockIdType BlockId, const void* NvM_SrcPtr);

/** Restore block default data [SWS_NvM_00467] */
Std_ReturnType NvM_RestoreBlockDefaults(NvM_BlockIdType BlockId, void* NvM_DstPtr);

/** Erase NV block [SWS_NvM_00468] */
Std_ReturnType NvM_EraseNvBlock(NvM_BlockIdType BlockId);

/** Invalidate NV block [SWS_NvM_00469] */
Std_ReturnType NvM_InvalidateNvBlock(NvM_BlockIdType BlockId);

/** Query job result [SWS_NvM_00015] */
Std_ReturnType NvM_GetErrorStatus(NvM_BlockIdType BlockId, NvM_RequestResultType* RequestResultPtr);

/** Cyclic processing [SWS_NvM_00464] */
void           NvM_MainFunction(void);

/** Version info [SWS_NvM_00020] */
void           NvM_GetVersionInfo(Std_VersionInfoType* versioninfo);

#endif /* NVM_H */
