/**
 * @file    Rte.h
 * @brief   AUTOSAR CP R25-11 — Runtime Environment (RTE)
 * @details Generated RTE skeleton compliant with
 *          AUTOSAR_CP_SWS_RTE (R25-11)
 *          Functional Cluster: Runtime Environment
 *
 * NOTE: In a real project this file is fully generated by the RTE generator
 *       (e.g., Vector DaVinci Developer) from ARXML. This is a hand-written
 *       skeleton for educational / reference purposes.
 *
 * AUTOSAR Document: AUTOSAR_CP_SWS_RTE
 * Version        : R25-11
 */
#ifndef RTE_H
#define RTE_H

#include "Std_Types.h"

/* ================================================================
 * RTE Error Codes  [SWS_Rte_01007]
 * ================================================================ */
typedef uint8 Rte_StatusType;

#define RTE_E_OK                ((Rte_StatusType)0x00u)  /**< No error */
#define RTE_E_INVALID           ((Rte_StatusType)0x01u)  /**< Data invalid */
#define RTE_E_MAX_AGE_EXCEEDED  ((Rte_StatusType)0x02u)  /**< Data too old */
#define RTE_E_NEVER_RECEIVED    ((Rte_StatusType)0x04u)  /**< Never received */
#define RTE_E_LIMIT             ((Rte_StatusType)0x08u)  /**< Queue overflow */
#define RTE_E_NO_DATA           ((Rte_StatusType)0x10u)  /**< No data available */
#define RTE_E_LOST_DATA         ((Rte_StatusType)0x20u)  /**< Data was overwritten */
#define RTE_E_COM_STOPPED       ((Rte_StatusType)0x40u)  /**< Communication stopped */
#define RTE_E_TIMEOUT           ((Rte_StatusType)0x80u)  /**< Timeout */

/* ================================================================
 * Rte_Instance type (for multi-instantiable components)
 * ================================================================ */
typedef void* Rte_Instance;

/* ================================================================
 * Application Data Types (project-specific, normally generated)
 * ================================================================ */
typedef float32  EngineSpeedType;       /**< RPM  */
typedef float32  EngineTemperatureType; /**< °C   */
typedef float32  BatteryVoltageType;    /**< V    */
typedef uint8    EngineRunningType;     /**< 0/1  */
typedef uint8    DiagRequestType;

/* ================================================================
 * Inter-Runnable Variables (IRV)
 * ================================================================ */
extern EngineSpeedType       Rte_Irv_EngineSpeed;
extern EngineTemperatureType Rte_Irv_EngineTemp;
extern BatteryVoltageType    Rte_Irv_BatteryVoltage;

/* ================================================================
 * Port Interfaces — Engine SWC
 * ================================================================ */

/** Sender-Receiver: Engine sends speed to other SWCs */
Rte_StatusType Rte_Write_EngineSWC_EngineSpeed(EngineSpeedType value);
Rte_StatusType Rte_Write_EngineSWC_EngineTemperature(EngineTemperatureType value);
Rte_StatusType Rte_Write_EngineSWC_EngineRunning(EngineRunningType value);

/** Sender-Receiver: Engine reads from other ports */
Rte_StatusType Rte_Read_EngineSWC_BatteryVoltage(BatteryVoltageType* value);

/** Client-Server: Engine calls diagnostic service */
Rte_StatusType Rte_Call_EngineSWC_ReportDiagEvent(uint16 EventId, uint8 Status);

/* ================================================================
 * Port Interfaces — Battery SWC
 * ================================================================ */
Rte_StatusType Rte_Write_BatterySWC_BatteryVoltage(BatteryVoltageType value);
Rte_StatusType Rte_Write_BatterySWC_BatteryCurrent(float32 value);

Rte_StatusType Rte_Read_BatterySWC_EngineRunning(EngineRunningType* value);

/** NvM mirror read/write via RTE [SWS_Rte_04504] */
Rte_StatusType Rte_Write_BatterySWC_NvMBatteryData(const void* data);
Rte_StatusType Rte_Read_BatterySWC_NvMBatteryData(void* data);

/* ================================================================
 * RTE Lifecycle
 * ================================================================ */
Std_ReturnType Rte_Start(void);
Std_ReturnType Rte_Stop(void);

#endif /* RTE_H */
