/**
 * @file    Rte.c
 * @brief   AUTOSAR CP R25-11 — Runtime Environment stub implementation
 * @details Provides in-memory inter-SWC communication for host-build testing.
 *          On target, this would be generated by the RTE generator.
 */
#include "Rte.h"
#include <string.h>

/* ================================================================
 * Internal Shared Data (IRV / S-R buffers)
 * ================================================================ */
EngineSpeedType       Rte_Irv_EngineSpeed    = 0.0f;
EngineTemperatureType Rte_Irv_EngineTemp     = 25.0f;
BatteryVoltageType    Rte_Irv_BatteryVoltage = 12.0f;

static EngineRunningType s_EngineRunning = 0u;
static float32           s_BatteryCurrent = 0.0f;

/* ================================================================
 * Engine SWC Ports
 * ================================================================ */
Rte_StatusType Rte_Write_EngineSWC_EngineSpeed(EngineSpeedType value) {
    Rte_Irv_EngineSpeed = value;
    return RTE_E_OK;
}

Rte_StatusType Rte_Write_EngineSWC_EngineTemperature(EngineTemperatureType value) {
    Rte_Irv_EngineTemp = value;
    return RTE_E_OK;
}

Rte_StatusType Rte_Write_EngineSWC_EngineRunning(EngineRunningType value) {
    s_EngineRunning = value;
    return RTE_E_OK;
}

Rte_StatusType Rte_Read_EngineSWC_BatteryVoltage(BatteryVoltageType* value) {
    if (value == NULL_PTR) { return RTE_E_INVALID; }
    *value = Rte_Irv_BatteryVoltage;
    return RTE_E_OK;
}

Rte_StatusType Rte_Call_EngineSWC_ReportDiagEvent(uint16 EventId, uint8 Status) {
    (void)EventId;
    (void)Status;
    /* On target: calls Dem_SetEventStatus() via RTE service port */
    return RTE_E_OK;
}

/* ================================================================
 * Battery SWC Ports
 * ================================================================ */
Rte_StatusType Rte_Write_BatterySWC_BatteryVoltage(BatteryVoltageType value) {
    Rte_Irv_BatteryVoltage = value;
    return RTE_E_OK;
}

Rte_StatusType Rte_Write_BatterySWC_BatteryCurrent(float32 value) {
    s_BatteryCurrent = value;
    return RTE_E_OK;
}

Rte_StatusType Rte_Read_BatterySWC_EngineRunning(EngineRunningType* value) {
    if (value == NULL_PTR) { return RTE_E_INVALID; }
    *value = s_EngineRunning;
    return RTE_E_OK;
}

static uint8 s_NvMBatteryData[16] = {0};

Rte_StatusType Rte_Write_BatterySWC_NvMBatteryData(const void* data) {
    if (data == NULL_PTR) { return RTE_E_INVALID; }
    memcpy(s_NvMBatteryData, data, sizeof(s_NvMBatteryData));
    return RTE_E_OK;
}

Rte_StatusType Rte_Read_BatterySWC_NvMBatteryData(void* data) {
    if (data == NULL_PTR) { return RTE_E_INVALID; }
    memcpy(data, s_NvMBatteryData, sizeof(s_NvMBatteryData));
    return RTE_E_OK;
}

/* ================================================================
 * RTE Lifecycle
 * ================================================================ */
Std_ReturnType Rte_Start(void) {
    /* Initialize shared data to safe defaults */
    Rte_Irv_EngineSpeed    = 0.0f;
    Rte_Irv_EngineTemp     = 25.0f;
    Rte_Irv_BatteryVoltage = 12.0f;
    s_EngineRunning        = 0u;
    return E_OK;
}

Std_ReturnType Rte_Stop(void) {
    return E_OK;
}
